import {
  BellIcon,
  Cloud,
  FileIcon,
  FileImageIcon,
  FileMusicIcon,
  FileTextIcon,
  FileVideoIcon,
  Heart,
  HeartIcon,
  HomeIcon,
  Lock,
  Search,
  Share2,
  Zap,
} from 'lucide-vue-next'

export const features = [
  {
    icon: Cloud,
    title: 'Secure Cloud Storage',
    description: 'Your files are safely stored in the cloud with enterprise-grade security',
  },
  {
    icon: Share2,
    title: 'Easy File Sharing',
    description: 'Share files and folders with anyone, anywhere, anytime',
  },
  {
    icon: Search,
    title: 'Smart Search',
    description: 'Find your files instantly with powerful search capabilities',
  },
  {
    icon: Lock,
    title: 'Privacy First',
    description: 'Your data is encrypted and only accessible by you',
  },
  {
    icon: Zap,
    title: 'Fast Upload',
    description: 'Lightning-fast file uploads with progress tracking',
  },
  {
    icon: Heart,
    title: 'Favorites',
    description: 'Mark important files as favorites for quick access',
  },
]

export const pricingPlans = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    description: 'Perfect for personal use',
    features: [
      '100 MB total storage',
      '30 MB max file size',
      'Basic file types (Images, PDFs, Text)',
      'Basic sharing',
      'Web access',
    ],
    limitations: ['Limited file types', 'Small storage capacity'],
    popular: false,
    cta: 'Get Started Free',
  },
  {
    name: 'Pro',
    price: '$9.99',
    period: 'per month',
    description: 'For professionals and small teams',
    features: [
      '5 GB total storage',
      '1 GB max file size',
      'All file types supported',
      'Advanced sharing options',
      'Priority support',
      'File versioning',
    ],
    limitations: [],
    popular: true,
    cta: 'Go Pro',
  },
  {
    name: 'Premium',
    price: '$19.99',
    period: 'per month',
    description: 'For power users and large teams',
    features: [
      '100 GB total storage',
      '30 GB max file size',
      'All file types supported',
      'Team collaboration',
      '24/7 premium support',
      'Advanced security features',
      'Custom branding',
    ],
    limitations: [],
    popular: false,
    cta: 'Go Premium',
  },
]
export const mainNavigation = [
  { name: 'Dashboard', href: '/dashboard', icon: HomeIcon },
  { name: 'Images', href: '/dashboard/images', icon: FileImageIcon },
  { name: 'Videos', href: '/dashboard/videos', icon: FileVideoIcon },
  { name: 'Audio', href: '/dashboard/audios', icon: FileMusicIcon },
  { name: 'Documents', href: '/dashboard/documents', icon: FileTextIcon },
  { name: 'Others', href: '/dashboard/others', icon: FileIcon },
]

export const secondaryNavigation = [
  { name: 'Favorites', href: '/dashboard/favorites', icon: HeartIcon },
  { name: 'Subscriptions', href: '/dashboard/subscriptions', icon: BellIcon },
]

import type { SelectFile } from './types'

export const mockFileData: Omit<SelectFile, 'icon'>[] = [
  {
    id: 'folder-1',
    userId: 'user-123',
    name: 'Documents',
    type: 'folder',
    size: 0,
    mimeType: null,
    path: '/Documents',
    url: null,
    category: null,
    isFavorited: false,
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-15T10:00:00Z'),
  },
  {
    id: 'folder-2',
    userId: 'user-123',
    name: 'Images',
    type: 'folder',
    size: 0,
    mimeType: null,
    path: '/Images',
    url: null,
    category: null,
    isFavorited: true,
    createdAt: new Date('2024-01-16T11:00:00Z'),
    updatedAt: new Date('2024-01-16T11:00:00Z'),
  },
  {
    id: 'folder-3',
    userId: 'user-123',
    name: 'Videos',
    type: 'folder',
    size: 0,
    mimeType: null,
    path: '/Videos',
    url: null,
    category: null,
    isFavorited: false,
    createdAt: new Date('2024-01-17T12:00:00Z'),
    updatedAt: new Date('2024-01-17T12:00:00Z'),
  },

  // Files in root
  {
    id: 'file-1',
    userId: 'user-123',
    name: 'readme.txt',
    type: 'file',
    size: 2048,
    mimeType: 'text/plain',
    path: '/readme.txt',
    url: 'https://example.com/files/readme.txt',
    category: 'documents',
    isFavorited: false,
    createdAt: new Date('2024-01-20T14:00:00Z'),
    updatedAt: new Date('2024-01-20T14:00:00Z'),
  },

  // Files in Documents folder
  {
    id: 'file-2',
    userId: 'user-123',
    name: 'report.pdf',
    type: 'file',
    size: 1048576,
    mimeType: 'application/pdf',
    path: '/Documents/report.pdf',
    url: 'https://example.com/files/report.pdf',
    category: 'documents',
    isFavorited: true,
    createdAt: new Date('2024-01-18T13:00:00Z'),
    updatedAt: new Date('2024-01-18T13:00:00Z'),
  },
  {
    id: 'file-3',
    userId: 'user-123',
    name: 'presentation.pptx',
    type: 'file',
    size: 2097152,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    path: '/Documents/presentation.pptx',
    url: 'https://example.com/files/presentation.pptx',
    category: 'documents',
    isFavorited: false,
    createdAt: new Date('2024-01-19T15:00:00Z'),
    updatedAt: new Date('2024-01-19T15:00:00Z'),
  },

  // Subfolder in Documents
  {
    id: 'folder-4',
    userId: 'user-123',
    name: 'Projects',
    type: 'folder',
    size: 0,
    mimeType: null,
    path: '/Documents/Projects',
    url: null,
    category: null,
    isFavorited: false,
    createdAt: new Date('2024-01-21T16:00:00Z'),
    updatedAt: new Date('2024-01-21T16:00:00Z'),
  },

  // Files in Images folder
  {
    id: 'file-4',
    userId: 'user-123',
    name: 'vacation.jpg',
    type: 'file',
    size: 524288,
    mimeType: 'image/jpeg',
    path: '/Images/vacation.jpg',
    url: 'https://picsum.photos/800/600?random=1',
    category: 'images',
    isFavorited: true,
    createdAt: new Date('2024-01-22T17:00:00Z'),
    updatedAt: new Date('2024-01-22T17:00:00Z'),
  },
  {
    id: 'file-5',
    userId: 'user-123',
    name: 'screenshot.png',
    type: 'file',
    size: 256000,
    mimeType: 'image/png',
    path: '/Images/screenshot.png',
    url: 'https://picsum.photos/800/600?random=2',
    category: 'images',
    isFavorited: false,
    createdAt: new Date('2024-01-23T18:00:00Z'),
    updatedAt: new Date('2024-01-23T18:00:00Z'),
  },

  // Files in Videos folder
  {
    id: 'file-6',
    userId: 'user-123',
    name: 'demo.mp4',
    type: 'file',
    size: 10485760,
    mimeType: 'video/mp4',
    path: '/Videos/demo.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'videos',
    isFavorited: false,
    createdAt: new Date('2024-01-24T19:00:00Z'),
    updatedAt: new Date('2024-01-24T19:00:00Z'),
  },

  // Files in Projects subfolder
  {
    id: 'file-7',
    userId: 'user-123',
    name: 'project-plan.xlsx',
    type: 'file',
    size: 131072,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    path: '/Documents/Projects/project-plan.xlsx',
    url: 'https://example.com/files/project-plan.xlsx',
    category: 'documents',
    isFavorited: false,
    createdAt: new Date('2024-01-25T20:00:00Z'),
    updatedAt: new Date('2024-01-25T20:00:00Z'),
  },
]
